### ISSUE TITLE
unable to start with Expo

### ISSUE THREAD

**Issue by stinghz** [notifme/swipehunt#1]
npm install
npm start
scan in Expo
got below error in console log

12:03:33 PM: Possible Unhandled Promise Rejection (id: 0):
Error: Failed to delete storage directory.Error Domain=NSCocoaErrorDomain Code=4 "“RCTAsyncLocalStorage” couldn’t be removed." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/ADC266DE-147D-4F5B-AD86-DD71B96FCB9C/Documents/ExponentExperienceData/%40anonymous%2Fhunty-ph-ba11c57f-2740-4495-a7c3-815a80344ef9/RCTAsyncLocalStorage, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x1702404b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
convertError@http://10.176.11.157:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:49180:22
http://10.176.11.157:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:49034:30
__invokeCallback@http://10.176.11.157:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:3438:21
http://10.176.11.157:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:3287:32
__guard@http://10.176.11.157:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:3374:11
invokeCallbackAndReturnFlushedQueue@http://10.176.11.157:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:3286:19
invokeCallbackAndReturnFlushedQueue@[native code]

**Comment by jnoleau** [comment]
Indeed I forget to push the correct way to clear the local storage.

Corrected by https://github.com/notifme/swipehunt/commit/e95ccb762df13a8aabb119f01e0eab33d3d6ae38
